# Generated by Django 4.2.9 on 2024-01-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=4)),
                ('plane', models.CharField(max_length=50)),
                ('rollCost', models.IntegerField(default=0)),
            ],
        ),
    ]
