# Generated by Django 4.2.9 on 2024-01-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
