# Generated by Django 4.2.9 on 2024-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0002_remove_session_id_alter_session_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
