# Generated by Django 4.2.9 on 2024-01-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0003_alter_session_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='plane',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
