# Generated by Django 4.2.9 on 2024-01-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0004_alter_session_plane_alter_session_session_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('set', models.CharField(max_length=3)),
                ('webcamFriendly', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='plane',
        ),
        migrations.AddField(
            model_name='session',
            name='plane_id',
            field=models.IntegerField(default=1),
        ),
    ]
