# Generated by Django 4.2.9 on 2024-01-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0005_plane_remove_session_plane_session_plane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='plane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planechaseSessions.plane'),
        ),
    ]
