# Generated by Django 4.2.9 on 2024-01-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0006_alter_session_plane_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='plane_id',
            new_name='plane',
        ),
    ]
