# Generated by Django 4.2.9 on 2024-01-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0007_rename_plane_id_session_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
