# Generated by Django 4.2.9 on 2024-01-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0008_alter_plane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
