# Generated by Django 4.2.9 on 2024-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0009_alter_plane_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='rollResult',
            field=models.CharField(default='Blank', max_length=10),
        ),
    ]
