# Generated by Django 4.2.9 on 2024-01-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0010_session_rollresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='planeDeck',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
