# Generated by Django 4.2.9 on 2024-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0011_session_planedeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='planeDeck',
            field=models.JSONField(default={}),
        ),
    ]
