# Generated by Django 4.2.9 on 2024-01-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0013_rename_planedeck_session_planardeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='planarDeck',
            field=models.JSONField(default=dict),
        ),
    ]
