# Generated by Django 4.2.9 on 2024-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planechaseSessions', '0014_alter_session_planardeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='discard',
            field=models.JSONField(default=dict),
        ),
    ]
